name: yuanchengbag
on:
  workflow_dispatch:
  schedule:
    - cron: '26 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuanchengbag
        env:
          qcm601: ${{ secrets.qcm601 }}
        run: |
          echo $qcm601 | jq -r .r37737 | /bin/bash
          echo $xmpy1457 | jq -r .y217 | /bin/bash
          echo $u057 | jq -r .b352 | /bin/bash
          echo $xauk2 | jq -r .vq095 | /bin/bash
          echo $q0966 | jq -r .nnj04229 | /bin/bash
          echo $nkt90528 | jq -r .alqgo0981 | /bin/bash
          echo $sqln5444 | jq -r .durej0 | /bin/bash

