name: yuanchengbag

on:
  workflow_dispatch:
  schedule:
    - cron: '52 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuanchengbag
        env:
          mdtr939: ${{ secrets.mdtr939 }}
        run: |
          echo $mdtr939 | jq -r .dh70 | /bin/bash
          echo $hsqc0162 | jq -r .rqaz50991 | /bin/bash
          echo $vbji3 | jq -r .gczrr5961 | /bin/bash
          echo $ofg4351 | jq -r .mmsq6 | /bin/bash
          echo $dz95 | jq -r .rev56 | /bin/bash
          echo $ikc8 | jq -r .oqsg79093 | /bin/bash
          echo $wjjr146 | jq -r .uk5796 | /bin/bash
          echo $q5 | jq -r .slw3 | /bin/bash

